---
runtime: go
api_version: go1
default_expiration: 300s
handlers:
- url: "/2010/censor-busting/"
  static_files: _site/2010/censor-busting/index.html
  upload: _site/2010/censor-busting/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/2010/epic-snow/"
  static_files: _site/2010/epic-snow/index.html
  upload: _site/2010/epic-snow/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/2011/everywhere-nowhere/"
  static_files: _site/2011/everywhere-nowhere/index.html
  upload: _site/2011/everywhere-nowhere/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/2011/alone-together/"
  static_files: _site/2011/alone-together/index.html
  upload: _site/2011/alone-together/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/2013/what-brands-can-learn-from-the-naacp/"
  static_files: _site/2013/what-brands-can-learn-from-the-naacp/index.html
  upload: _site/2013/what-brands-can-learn-from-the-naacp/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/2014/vint-cerf/"
  static_files: _site/2014/vint-cerf/index.html
  upload: _site/2014/vint-cerf/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/2016/snowzilla/"
  static_files: _site/2016/snowzilla/index.html
  upload: _site/2016/snowzilla/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/2016/syracuse/"
  static_files: _site/2016/syracuse/index.html
  upload: _site/2016/syracuse/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/404.html"
  static_files: _site/404.html
  upload: _site/404.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/about/"
  static_files: _site/about/index.html
  upload: _site/about/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/bio/"
  static_files: _site/bio/index.html
  upload: _site/bio/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/data/"
  static_files: _site/data/index.html
  upload: _site/data/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/feed.xml"
  static_files: _site/feed.xml
  upload: _site/feed.xml
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/"
  static_files: _site/index.html
  upload: _site/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/site/"
  static_files: _site/site/index.html
  upload: _site/site/index.html
  http_headers:
    Link: "</assets/css/style.css>; rel=preload; as=style,"
- url: "/assets/"
  static_dir: _site/assets
