<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Ben Murray | Stories &amp; Observations</title>
  <link rel="shortcut icon" href="/assets/images/favicon.ico">
  <link rel="stylesheet" href="/assets/css/style.css">
  <link rel="alternate" type="application/rss+xml" title="Ben Murray" href="/rss.xml">
  <link rel="stylesheet" href="/assets/css/highlight.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  
</head>
<body>

  <nav class="main-nav">
    
        <a href="/"> <span class="arrow">←</span> Home </a>
    

    
        
            <a href="/about">About </a>
        
    
	<a href="http://hi.benmurray.us">Moments</a>
	<a href="http://photos.benmurray.us">Photos</a>
	<a href="http://www.facebook.com/benmurray"><i class="fa fa-facebook"></i></a>
	<a href="http://www.instagram.com/bnmry"><i class="fa fa-instagram"></i></a>
	<a href="http://www.twitter.com/bmurray"><i class="fa fa-twitter"></i></a>
    <!-- <a class="cta" href="/feed.xml">Subscribe</a> -->
	
</nav>

  

  <section id="wrapper" class="">
    ---
runtime: go
api_version: go1
default_expiration: 300s
handlers:
- url: "/2010/censor-busting/"
  static_files: _site/2010/censor-busting/index.html
  upload: _site/2010/censor-busting/index.html
- url: "/2010/epic-snow/"
  static_files: _site/2010/epic-snow/index.html
  upload: _site/2010/epic-snow/index.html
- url: "/2011/everywhere-nowhere/"
  static_files: _site/2011/everywhere-nowhere/index.html
  upload: _site/2011/everywhere-nowhere/index.html
- url: "/2011/alone-together/"
  static_files: _site/2011/alone-together/index.html
  upload: _site/2011/alone-together/index.html
- url: "/2013/what-brands-can-learn-from-the-naacp/"
  static_files: _site/2013/what-brands-can-learn-from-the-naacp/index.html
  upload: _site/2013/what-brands-can-learn-from-the-naacp/index.html
- url: "/2014/vint-cerf/"
  static_files: _site/2014/vint-cerf/index.html
  upload: _site/2014/vint-cerf/index.html
- url: "/2016/snowzilla/"
  static_files: _site/2016/snowzilla/index.html
  upload: _site/2016/snowzilla/index.html
- url: "/404.html"
  static_files: _site/404.html
  upload: _site/404.html
- url: "/about/"
  static_files: _site/about/index.html
  upload: _site/about/index.html
- url: "/feed.xml"
  static_files: _site/feed.xml
  upload: _site/feed.xml
- url: "/"
  static_files: _site/index.html
  upload: _site/index.html
- url: "/site/"
  static_files: _site/site/index.html
  upload: _site/site/index.html
- url: "/CNAME"
  static_files: _site/CNAME
  upload: _site/CNAME
- url: "/Gemfile"
  static_files: _site/Gemfile
  upload: _site/Gemfile
- url: "/Gemfile.lock"
  static_files: _site/Gemfile.lock
  upload: _site/Gemfile.lock
- url: "/LICENSE"
  static_files: _site/LICENSE
  upload: _site/LICENSE
- url: "/README.md"
  static_files: _site/README.md
  upload: _site/README.md
- url: "/assets/css/highlight.css"
  static_files: _site/assets/css/highlight.css
  upload: _site/assets/css/highlight.css
- url: "/assets/css/style.css"
  static_files: _site/assets/css/style.css
  upload: _site/assets/css/style.css
- url: "/assets/fonts/icons.eot"
  static_files: _site/assets/fonts/icons.eot
  upload: _site/assets/fonts/icons.eot
- url: "/assets/fonts/icons.svg"
  static_files: _site/assets/fonts/icons.svg
  upload: _site/assets/fonts/icons.svg
- url: "/assets/fonts/icons.ttf"
  static_files: _site/assets/fonts/icons.ttf
  upload: _site/assets/fonts/icons.ttf
- url: "/assets/fonts/icons.woff"
  static_files: _site/assets/fonts/icons.woff
  upload: _site/assets/fonts/icons.woff
- url: "/assets/images/2016/BRM-20160123-Snowzilla-5245.jpg"
  static_files: _site/assets/images/2016/BRM-20160123-Snowzilla-5245.jpg
  upload: _site/assets/images/2016/BRM-20160123-Snowzilla-5245.jpg
- url: "/assets/images/2016/BRM-20160123-Snowzilla-5271.jpg"
  static_files: _site/assets/images/2016/BRM-20160123-Snowzilla-5271.jpg
  upload: _site/assets/images/2016/BRM-20160123-Snowzilla-5271.jpg
- url: "/assets/images/2016/BRM-20160123-Snowzilla-5307.jpg"
  static_files: _site/assets/images/2016/BRM-20160123-Snowzilla-5307.jpg
  upload: _site/assets/images/2016/BRM-20160123-Snowzilla-5307.jpg
- url: "/assets/images/2016/BRM-20160123-Snowzilla-5308.jpg"
  static_files: _site/assets/images/2016/BRM-20160123-Snowzilla-5308.jpg
  upload: _site/assets/images/2016/BRM-20160123-Snowzilla-5308.jpg
- url: "/assets/images/2016/snowzilla1.jpg"
  static_files: _site/assets/images/2016/snowzilla1.jpg
  upload: _site/assets/images/2016/snowzilla1.jpg
- url: "/assets/images/brm-photo.gif"
  static_files: _site/assets/images/brm-photo.gif
  upload: _site/assets/images/brm-photo.gif
- url: "/assets/images/brm-stamp.gif"
  static_files: _site/assets/images/brm-stamp.gif
  upload: _site/assets/images/brm-stamp.gif
- url: "/assets/images/favicon.ico"
  static_files: _site/assets/images/favicon.ico
  upload: _site/assets/images/favicon.ico
- url: "/assets/js/highlight.js"
  static_files: _site/assets/js/highlight.js
  upload: _site/assets/js/highlight.js
- url: "/assets/js/main.js"
  static_files: _site/assets/js/main.js
  upload: _site/assets/js/main.js
- url: "/untitled.py"
  static_files: _site/untitled.py
  upload: _site/untitled.py

  </section>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="/assets/js/main.js"></script>
  <script src="/assets/js/highlight.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-504797-6', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>



